app/dept_qa/urls.py
from django.urls import path
from . import views

app_name = 'app.dept_qa'

urlpatterns = [
    path('generate-checklist/', views.GenerateChecklistView.as_view(), name='generate_checklist'),
    path('checklist/iris-<str:iris_number>/', views.ChecklistDetailView.as_view(), name='checklist_detail'),
    path('customer-autocomplete/', views.CustomerAutocompleteView.as_view(), name='customer_autocomplete'),
    # Add more URLs as needed
]

app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('qa/', include('app.dept_qa.urls', namespace='dept_qa')),
]

app/templates/includes/components_field.html
<div>
    <label>{{ field.label }}</label>
    {% for component_type, components in component_groups.items %}
        <fieldset class="mt-4">
            <legend class="font-semibold">{{ component_type.name }}</legend>
            {% for component in components %}
                <div class="flex items-center mt-2">
                    <input type="checkbox" name="{{ field.html_name }}" value="{{ component.id }}"
                        id="component_{{ component.id }}"
                        {% if component.id|stringformat:"s" in field.value|stringformat:"s" %}checked{% endif %}
                        class="checkbox checkbox-primary">
                    <label for="component_{{ component.id }}" class="ml-2">{{ component.name }}</label>
                </div>
            {% endfor %}
        </fieldset>
    {% endfor %}
</div>

app/templates/includes/footer.html
<footer class="footer p-4 bg-neutral text-neutral-content">
    <div class="items-center grid-flow-col">
      <img src="" alt="ATG Logo" class="h-8 w-8 mr-2">
      <p>&copy; {{ now|date:"Y" }} ATG. All rights reserved.</p>
    </div>
    <div class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
      <!-- Social media icons or additional links -->
    </div>
  </footer>
  

app/templates/includes/navbar.html
<nav class="navbar bg-base-100">
    <div class="navbar-start">
      <a href="" class="btn btn-ghost normal-case text-xl">
        <img src="" alt="ATG Logo" class="h-8 w-8 mr-2">
        ATG Tools
      </a>
    </div>
    <div class="navbar-center hidden lg:flex">
      <ul class="menu menu-horizontal p-0">
        <li><a href="">Home</a></li>
        <li><a href="{% url 'dept_qa:generate_checklist' %}">Generate Checklist</a></li>
        <!-- Add more links as needed -->
      </ul>
    </div>
    <div class="navbar-end">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img src="" alt="User Avatar" />
          </div>
        </label>
        <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52">
          <li>
            <a href="" class="justify-between">
              Profile
              <!-- You can add a badge or notification count here -->
            </a>
          </li>
          <li><a href="{% url 'account_logout' %}">Logout</a></li>
        </ul>
      </div>
    </div>
</nav>
  